
import { PetStyle, Goal } from './types';

export const PET_STYLES: Record<'dog' | 'cat', PetStyle[]> = {
  dog: [
    { id: 'golden', primary: '#FBBF24', secondary: '#FDE68A', accent: '#FEF3C7', pattern: 'solid', labelEn: 'Golden Retriever', labelEs: 'Golden Retriever' },
    { id: 'shepherd', primary: '#92400E', secondary: '#1F2937', accent: '#D97706', pattern: 'saddle', labelEn: 'German Shepherd', labelEs: 'Pastor Alemán' },
    { id: 'poodle', primary: '#F3F4F6', secondary: '#E5E7EB', accent: '#D1D5DB', pattern: 'solid', labelEn: 'Poodle', labelEs: 'Caniche' },
    { id: 'bulldog', primary: '#D97706', secondary: '#FFFFFF', accent: '#FED7AA', pattern: 'spots', labelEn: 'Bulldog', labelEs: 'Bulldog' },
    { id: 'beagle', primary: '#78350F', secondary: '#1F2937', accent: '#FFFFFF', pattern: 'saddle', labelEn: 'Beagle', labelEs: 'Beagle' },
  ],
  cat: [
    { id: 'persian', primary: '#FFFFFF', secondary: '#F3F4F6', accent: '#E5E7EB', pattern: 'solid', labelEn: 'Persian', labelEs: 'Persa' },
    { id: 'siamese', primary: '#F5F5F4', secondary: '#44403C', accent: '#A8A29E', pattern: 'points', labelEn: 'Siamés', labelEs: 'Siamés' },
    { id: 'maine', primary: '#4B5563', secondary: '#1F2937', accent: '#9CA3AF', pattern: 'spots', labelEn: 'Maine Coon', labelEs: 'Maine Coon' },
    { id: 'bengal', primary: '#D97706', secondary: '#451A03', accent: '#F59E0B', pattern: 'spots', labelEn: 'Bengala', labelEs: 'Bengala' },
    { id: 'ragdoll', primary: '#F0F9FF', secondary: '#1E40AF', accent: '#DBEAFE', pattern: 'points', labelEn: 'Ragdoll', labelEs: 'Ragdoll' },
  ]
};

export const GOAL_BANK: Goal[] = [
  // RUNNING CHALLENGES (1-15)
  { id: 1, category: 'Running', en: "Let's run {X}km at your own pace today", es: "Corramos {X}km a tu propio ritmo hoy", baseValue: 2, isPhysical: true, exampleEn: "Find a flat route and keep a pace where you can still talk.", exampleEs: "Busca una ruta plana y mantén un ritmo al que todavía puedas hablar." },
  { id: 2, category: 'Running', en: "Let's do an easy {X}km jog and walk whenever you need to today", es: "Hagamos un trote suave de {X}km y camina cuando lo necesites hoy", baseValue: 2, isPhysical: true, exampleEn: "Alternate between 2 mins of jogging and 1 min of walking.", exampleEs: "Alterna entre 2 min de trote y 1 min de caminata." },
  { id: 3, category: 'Running', en: "Let's run {X}km and focus only on breathing, not speed today", es: "Corramos {X}km y enfócate solo en la respiración, no en la velocidad hoy", baseValue: 3, isPhysical: true, exampleEn: "Inhale for 3 steps, exhale for 3 steps. Keep it steady.", exampleEs: "Inhala durante 3 pasos, exhala durante 3 pasos. Mantén la constancia." },
  { id: 4, category: 'Running', en: "Let's do {X} minutes of interval running — 1 min fast, 1 min walk today", es: "Hagamos {X} minutos de carrera por intervalos: 1 min rápido, 1 min caminando hoy", baseValue: 20, isPhysical: true, exampleEn: "Warm up for 5 mins, then repeat the 1:1 intervals.", exampleEs: "Calienta 5 min, luego repite los intervalos 1:1." },
  { id: 5, category: 'Running', en: "Let's run {X}km without stopping — just a steady comfortable pace today", es: "Corramos {X}km sin parar, solo a un ritmo constante y cómodo hoy", baseValue: 3, isPhysical: true, exampleEn: "Don't start too fast. Save energy for the final kilometer.", exampleEs: "No empieces demasiado rápido. Reserva energía para el último kilómetro." },
  { id: 6, category: 'Running', en: "Let's do a fartlek run for {X} minutes — speed up when you feel like it today", es: "Hagamos un fartlek de {X} minutos: acelera cuando te apetezca hoy", baseValue: 25, isPhysical: true, exampleEn: "Use landmarks like trees or lamps to set your fast segments.", exampleEs: "Usa puntos de referencia como árboles o farolas para tus tramos rápidos." },
  { id: 7, category: 'Running', en: "Let's run {X}km and notice how your body feels at each kilometer today", es: "Corramos {X}km y nota cómo se siente tu cuerpo en cada kilómetro hoy", baseValue: 4, isPhysical: true, exampleEn: "Scan from head to toe. Are your shoulders relaxed?", exampleEs: "Escanea de pies a cabeza. ¿Están tus hombros relajados?" },
  { id: 8, category: 'Running', en: "Let's do a slow {X}km recovery jog — slower than your usual pace today", es: "Hagamos un trote de recuperación lento de {X}km, más lento que tu ritmo habitual hoy", baseValue: 2, isPhysical: true, exampleEn: "This should feel very easy. Focus on moving your legs gently.", exampleEs: "Esto debería ser muy fácil. Concéntrate en mover las piernas suavemente." },
  { id: 9, category: 'Running', en: "Let's run {X}km on a route you haven't tried before today", es: "Corramos {X}km por una ruta que no hayas probado antes hoy", baseValue: 3, isPhysical: true, exampleEn: "Explore a new park or a different neighborhood street.", exampleEs: "Explora un parque nuevo o una calle diferente del barrio." },
  { id: 10, category: 'Running', en: "Let's do {X} minutes of easy running and end with a 2 minute walk today", es: "Hagamos {X} minutos de carrera suave y termina con una caminata de 2 minutos hoy", baseValue: 15, isPhysical: true, exampleEn: "Keep the intensity low. The walk at the end is for cooling down.", exampleEs: "Mantén la intensidad baja. La caminata final es para enfriar." },
  { id: 11, category: 'Running', en: "Let's run {X}km and dedicate each kilometer to something you are grateful for today", es: "Corramos {X}km y dedica cada kilómetro a algo por lo que estés agradecido hoy", baseValue: 3, isPhysical: true, exampleEn: "Think of one person or thing you appreciate during each km.", exampleEs: "Piensa en una persona o cosa que aprecies durante cada km." },
  { id: 12, category: 'Running', en: "Let's do a {X}km progression run — start slow and finish slightly faster today", es: "Hagamos una carrera de progresión de {X}km: empieza despacio y termina un poco más rápido hoy", baseValue: 4, isPhysical: true, exampleEn: "Increase your speed by about 10-15 seconds per km.", exampleEs: "Aumenta tu velocidad unos 10-15 segundos por km." },
  { id: 13, category: 'Running', en: "Let's run {X}km with a friend or running buddy today", es: "Corramos {X}km con un amigo o compañero de carrera hoy", baseValue: 3, isPhysical: true, exampleEn: "Social running makes the distance feel shorter. Keep it chatty.", exampleEs: "Correr en compañía hace que la distancia parezca menor. Hablad." },
  { id: 14, category: 'Running', en: "Let's do {X} minutes of hill walking or incline running today", es: "Hagamos {X} minutos de caminata en colina o carrera con inclinación hoy", baseValue: 20, isPhysical: true, exampleEn: "Find a steady incline. Lean forward slightly and use your arms.", exampleEs: "Busca una pendiente constante. Inclínate un poco y usa los brazos." },
  { id: 15, category: 'Running', en: "Let's run {X}km and stop for 30 seconds every kilometer to breathe today", es: "Corramos {X}km y para 30 segundos cada kilómetro para respirar hoy", baseValue: 5, isPhysical: true, exampleEn: "Use the breaks to reset your form and lower your heart rate.", exampleEs: "Usa los descansos para corregir tu postura y bajar las pulsaciones." },

  // WALKING CHALLENGES (16-25)
  { id: 16, category: 'Walking', en: "Let's walk for {X} minutes at a comfortable pace today", es: "Caminemos durante {X} minutos a un ritmo cómodo hoy", baseValue: 20, isPhysical: true, exampleEn: "A brisk walk where you can still hold a conversation.", exampleEs: "Una caminata rápida en la que aún puedas mantener una conversación." },
  { id: 17, category: 'Walking', en: "Let's take {X} steps today — any pace counts", es: "Demos {X} pasos hoy, cualquier ritmo cuenta", baseValue: 5000, isPhysical: true, exampleEn: "Park further away or take a quick loop around the block.", exampleEs: "Aparca más lejos o da una vuelta rápida a la manzana." },
  { id: 18, category: 'Walking', en: "Let's walk for {X} minutes with no phone — just you and the road today", es: "Caminemos durante {X} minutos sin teléfono, solo tú y el camino hoy", baseValue: 15, isPhysical: true, exampleEn: "Leave your device at home and focus on the sounds around you.", exampleEs: "Deja el dispositivo en casa y fíjate en los sonidos ambientales." },
  { id: 19, category: 'Walking', en: "Let's do a {X} minute mindful walk and notice 3 new things around you today", es: "Hagamos una caminata consciente de {X} minutos y nota 3 cosas nuevas a tu alrededor hoy", baseValue: 10, isPhysical: true, exampleEn: "Look for details in nature or architecture you usually miss.", exampleEs: "Busca detalles en la naturaleza o arquitectura que suelas ignorar." },
  { id: 20, category: 'Walking', en: "Let's walk for {X} minutes and listen to something you enjoy today", es: "Caminemos durante {X} minutos y escucha algo que disfrutes hoy", baseValue: 30, isPhysical: true, exampleEn: "Pick a podcast, audiobook, or your favorite playlist.", exampleEs: "Elige un podcast, audiolibro o tu lista de reproducción favorita." },
  { id: 21, category: 'Walking', en: "Let's take a {X} minute walk after your biggest meal today", es: "Demos un paseo de {X} minutos después de tu comida más copiosa hoy", baseValue: 15, isPhysical: true, exampleEn: "Gentle movement helps digestion and prevents energy crashes.", exampleEs: "El movimiento suave ayuda a la digestión y evita bajones de energía." },
  { id: 22, category: 'Walking', en: "Let's walk {X} minutes with someone you care about today", es: "Caminemos {X} minutos con alguien que te importe hoy", baseValue: 20, isPhysical: true, exampleEn: "Invite a family member or call a friend while you walk.", exampleEs: "Invita a un familiar o llama a un amigo mientras caminas." },
  { id: 23, category: 'Walking', en: "Let's do a slow {X} minute evening walk to wind down today", es: "Hagamos una caminata nocturna lenta de {X} minutos para relajarnos hoy", baseValue: 15, isPhysical: true, exampleEn: "Keep the pace very relaxed to prepare your body for sleep.", exampleEs: "Mantén un ritmo muy relajado para preparar tu cuerpo para dormir." },
  { id: 24, category: 'Walking', en: "Let's walk to somewhere nearby instead of driving — aim for {X} minutes today", es: "Camina a algún lugar cercano en lugar de conducir: intenta que sean {X} minutos hoy", baseValue: 10, isPhysical: true, exampleEn: "Walk to the store, the post office, or a local cafe.", exampleEs: "Ve andando a la tienda, a correos o a una cafetería cercana." },
  { id: 25, category: 'Walking', en: "Let's take the stairs and add a {X} minute walk somewhere in your day today", es: "Usa las escaleras y añade una caminata de {X} minutos en algún momento de tu día hoy", baseValue: 10, isPhysical: true, exampleEn: "Skip the elevator and find a 10-min slot for extra steps.", exampleEs: "Evita el ascensor y busca un hueco de 10 min para dar más pasos." },

  // WARM-UP AND COOL-DOWN CHALLENGES (26-35)
  { id: 26, category: 'Warm-up', en: "Let's do a {X} minute dynamic warm-up before heading out today", es: "Hagamos un calentamiento dinámico de {X} minutos antes de salir hoy", baseValue: 5, isPhysical: true, exampleEn: "Include leg swings, arm circles, and torso twists.", exampleEs: "Incluye balanceos de piernas, círculos con los brazos y giros de tronco." },
  { id: 27, category: 'Warm-up', en: "Let's spend {X} minutes stretching our legs before the run today", es: "Pasemos {X} minutos estirando las piernas antes de la carrera hoy", baseValue: 5, isPhysical: true, exampleEn: "Focus on dynamic stretches like walking lunges.", exampleEs: "Céntrate en estiramientos dinámicos como zancadas caminando." },
  { id: 28, category: 'Warm-up', en: "Let's do {X} minutes of light leg swings and hip circles before running today", es: "Hagamos {X} minutos de balanceos suaves de piernas y círculos de cadera antes de correr hoy", baseValue: 5, isPhysical: true, exampleEn: "Hold onto a wall for balance if needed. 10 reps each side.", exampleEs: "Apóyate en una pared si lo necesitas. 10 repeticiones por lado." },
  { id: 29, category: 'Cool-down', en: "Let's finish today's run with a {X} minute cool-down walk today", es: "Terminemos la carrera de hoy con una caminata de enfriamiento de {X} minutos hoy", baseValue: 5, isPhysical: true, exampleEn: "Slowly decrease your pace until your heart rate is back to normal.", exampleEs: "Reduce el ritmo poco a poco hasta que tus pulsaciones se normalicen." },
  { id: 30, category: 'Cool-down', en: "Let's do {X} minutes of post-run stretching focusing on calves today", es: "Hagamos {X} minutos de estiramientos post-carrera enfocándonos en las pantorrillas hoy", baseValue: 5, isPhysical: true, exampleEn: "Hold each stretch for 30 seconds. Don't bounce.", exampleEs: "Mantén cada estiramiento 30 segundos. No rebotes." },
  { id: 31, category: 'Cool-down', en: "Let's spend {X} minutes on a full lower body stretch after running today", es: "Pasemos {X} minutos en un estiramiento completo de la parte inferior del cuerpo después de correr hoy", baseValue: 10, isPhysical: true, exampleEn: "Stretch quads, hamstrings, glutes, and calves.", exampleEs: "Estira cuádriceps, isquiotibiales, glúteos y pantorrillas." },
  { id: 32, category: 'Recovery', en: "Let's do {X} minutes of foam rolling on quads and hamstrings today", es: "Hagamos {X} minutos de foam rolling en cuádriceps e isquiotibiales hoy", baseValue: 10, isPhysical: true, exampleEn: "Roll slowly and pause on any tight spots for 20 seconds.", exampleEs: "Rueda despacio y para en los puntos de tensión durante 20 segundos." },
  { id: 33, category: 'Warm-up', en: "Let's do a {X} minute warm-up jog before picking up the pace today", es: "Hagamos un trote de calentamiento de {X} minutos antes de acelerar el ritmo hoy", baseValue: 10, isPhysical: true, exampleEn: "Start at a very slow pace, almost a fast walk.", exampleEs: "Empieza a un ritmo muy lento, casi como una caminata rápida." },
  { id: 34, category: 'Warm-up', en: "Let's spend {X} minutes on ankle circles and calf raises before running today", es: "Pasemos {X} minutos haciendo círculos de tobillo y elevaciones de talón antes de correr hoy", baseValue: 5, isPhysical: true, exampleEn: "Wake up your lower legs to prevent injuries.", exampleEs: "Activa la parte inferior de las piernas para evitar lesiones." },
  { id: 35, category: 'Cool-down', en: "Let's finish with {X} minutes of deep breathing and light stretching today", es: "Terminemos con {X} minutos de respiración profunda y estiramientos suaves hoy", baseValue: 5, isPhysical: true, exampleEn: "Sit or lie down. Focus on long, slow exhales.", exampleEs: "Siéntate o túmbate. Céntrate en exhalaciones largas y lentas." },

  // RECOVERY CHALLENGES (36-43)
  { id: 36, category: 'Recovery', en: "Let's take a full rest day and let our legs recover for {X} minutes of light stretching today", es: "Tomemos un día de descanso completo y deja que tus piernas se recuperen con {X} minutos de estiramientos suaves hoy", baseValue: 15, isPhysical: false, exampleEn: "Rest is when the muscles actually get stronger. Enjoy it.", exampleEs: "El descanso es cuando los músculos se fortalecen. Disfrútalo." },
  { id: 37, category: 'Recovery', en: "Let's spend {X} minutes lying down with legs elevated after running today", es: "Pasemos {X} minutos tumbados con las piernas elevadas después de correr hoy", baseValue: 10, isPhysical: false, exampleEn: "Prop your legs up against a wall to help circulation.", exampleEs: "Apoya las piernas contra la pared para ayudar a la circulación." },
  { id: 38, category: 'Recovery', en: "Let's do {X} minutes of gentle yoga or floor stretching today", es: "Hagamos {X} minutos de yoga suave o estiramientos en el suelo hoy", baseValue: 20, isPhysical: true, exampleEn: "Follow a simple routine focused on hip mobility.", exampleEs: "Sigue una rutina sencilla centrada en la movilidad de la cadera." },
  { id: 39, category: 'Recovery', en: "Let's take a cold or warm shower for {X} minutes to help muscles recover today", es: "Date una ducha fría o caliente durante {X} minutos para ayudar a los músculos a recuperarse hoy", baseValue: 10, isPhysical: false, exampleEn: "Alternating temperatures can also help with inflammation.", exampleEs: "Alternar temperaturas también puede ayudar con la inflamación." },
  { id: 40, category: 'Recovery', en: "Let's sleep {X} hours tonight — set that intention before bed today", es: "Duerme {X} horas esta noche: establece esa intención antes de acostarte hoy", baseValue: 8, isPhysical: false, exampleEn: "Turn off screens 30 mins before your target bedtime.", exampleEs: "Apaga las pantallas 30 min antes de la hora prevista para dormir." },
  { id: 41, category: 'Recovery', en: "Let's do {X} minutes of light walking to shake out tired legs today", es: "Hagamos {X} minutos de caminata ligera para soltar las piernas cansadas hoy", baseValue: 15, isPhysical: true, exampleEn: "Active recovery helps clear metabolic waste from muscles.", exampleEs: "La recuperación activa ayuda a eliminar desechos metabólicos." },
  { id: 42, category: 'Recovery', en: "Let's spend {X} minutes reading or resting completely today", es: "Pasemos {X} minutos leyendo o descansando completamente hoy", baseValue: 30, isPhysical: false, exampleEn: "Mental rest is just as important as physical rest.", exampleEs: "El descanso mental es tan importante como el físico." },
  { id: 43, category: 'Recovery', en: "Let's do {X} minutes of body scan — lie still and notice where tension is today", es: "Hagamos {X} minutos de escaneo corporal: quédate quieto y nota dónde hay tensión hoy", baseValue: 10, isPhysical: false, exampleEn: "Start from your toes and work up to your head.", exampleEs: "Empieza por los dedos de los pies y sube hasta la cabeza." },

  // HYDRATION CHALLENGES (44-50)
  { id: 44, category: 'Hydration', en: "Let's drink {X} liters of water throughout the day today", es: "Bebamos {X} litros de agua a lo largo del día hoy", baseValue: 2, isPhysical: false, exampleEn: "Keep a water bottle with you at all times.", exampleEs: "Lleva siempre contigo una botella de agua." },
  { id: 45, category: 'Hydration', en: "Let's drink a full glass of water right now before anything else today", es: "Bebe un vaso lleno de agua ahora mismo antes de cualquier otra cosa hoy", baseValue: 1, isPhysical: false, exampleEn: "Hydrating first thing in the morning is a great habit.", exampleEs: "Hidratarse a primera hora de la mañana es un gran hábito." },
  { id: 46, category: 'Hydration', en: "Let's hydrate before heading out — drink {X}ml before the run today", es: "Hidrátate antes de salir: bebe {X}ml antes de la carrera hoy", baseValue: 300, isPhysical: false, exampleEn: "Drink this about 30-45 minutes before you start.", exampleEs: "Bebe esto unos 30-45 minutos antes de empezar." },
  { id: 47, category: 'Hydration', en: "Let's rehydrate within 30 minutes of finishing — drink {X}ml today", es: "Rehidrátate a los 30 minutos de terminar: bebe {X}ml hoy", baseValue: 500, isPhysical: false, exampleEn: "Your body needs fluids to start the recovery process.", exampleEs: "Tu cuerpo necesita líquidos para iniciar la recuperación." },
  { id: 48, category: 'Hydration', en: "Let's swap one drink for water and hit {X} glasses total today", es: "Cambia una bebida por agua y alcanza los {X} vasos en total hoy", baseValue: 8, isPhysical: false, exampleEn: "Replace soda or juice with plain or sparkling water.", exampleEs: "Sustituye el refresco o zumo por agua natural o con gas." },
  { id: 49, category: 'Hydration', en: "Let's add electrolytes after today's run — coconut water or a tablet counts today", es: "Añade electrolitos después de la carrera de hoy: el agua de coco o una pastilla cuentan hoy", baseValue: 1, isPhysical: false, exampleEn: "Electrolytes help balance minerals lost through sweat.", exampleEs: "Los electrolitos ayudan a equilibrar los minerales perdidos por el sudor." },
  { id: 50, category: 'Hydration', en: "Let's track every glass of water and hit {X} liters before 8pm today", es: "Registra cada vaso de agua y alcanza los {X} litros antes de las 8 p.m. hoy", baseValue: 2, isPhysical: false, exampleEn: "Use an app or a simple tally on paper to track.", exampleEs: "Usa una app o una simple cuenta en papel para el registro." },
];

export const FEEDBACK_MESSAGES = [
  { en: "Good job! Keep it up.", es: "¡Buen trabajo! Sigue así." },
  { en: "Amazing! You're achieving a lot today.", es: "¡Increíble! Estás logrando mucho hoy." },
  { en: "That's it! Your pet is proud of you.", es: "¡Eso es! Tu mascota está orgullosa de ti." },
  { en: "What a great step towards your wellbeing!", es: "¡Qué gran paso hacia tu bienestar!" },
  { en: "You did it! You are unstoppable.", es: "¡Lo lograste! Eres imparable." }
];

export const UI_STRINGS = {
  en: {
    start: 'Start your journey',
    continue: 'Continue',
    startJourney: 'Start the journey',
    nameYourPet: 'Name your pet (optional)',
    petNamingDialogue: '“Names matter. This is the start of your journey together.”',
    petGrow: 'Your pet will grow with you.',
    shareTitle: 'Would you like to take care of {petName} with someone?',
    shareSub: 'You can invite someone later — support grows over time.',
    justMe: 'Just me',
    shareMyPet: 'Share my pet',
    copyLink: 'Copy Link',
    linkCopied: 'Link copied! 🔗',
    todayGoals: 'Today’s Goals',
    simulateNext: 'Simulate Next Day',
    petStatus: 'Pet Status',
    dashboardWelcome: 'I’m glad you’re here. Let’s take today one step at a time.',
    nextDayMessage: 'Every day is a new chance. I’m happy you’re here.',
    whatGender: 'Choose Pet Gender',
    petGenderDialogue: '“Your pet reflects you, not labels.”',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    whatIsYourName: 'Nice to meet you! What is your name?',
    userNameDialogue: '“I’ll use this when checking in with you.”',
    userNamePlaceholder: 'Your name...',
    customizationNote: 'We will customize your experience with this information.',
    whatUserGender: 'How do you identify?',
    userMale: 'Male',
    userFemale: 'Female',
    userNonBinary: 'Non-binary',
    preferNotToAnswer: 'Prefer not to say',
    intro1Title: 'AI Missions',
    intro1Text: '“I’ll create daily missions that adapt to your life, energy, and time.”',
    intro2Title: 'Better Together',
    intro2Text: '“You can grow alone, or share this journey with someone you care about.”',
    intro3Title: 'Safe Space',
    intro3Text: '“Missing a day won’t hurt your progress. We always adapt.”',
    thinkingTitle: 'is thinking...',
    thinkingText: '“Creating personalized tasks based on your tastes...”',
    userAgeTitle: 'What is your age range?',
    userAgeDialogue: '“This helps me tailor challenges safely.”',
    userGenderTitle: 'Gender Identity',
    userGenderDialogue: '“Only if you’re comfortable sharing.”',
    userAgeToday: 'How are you feeling today,',
    userTimeToday: 'How much time do you have today?',
    userEnergyToday: 'Your energy today?',
    thinkingText2: '“Creating personalized tasks based on your tastes...”',
    userActivityTitle: 'How often do you go for a run or walk each week?',
    userActivityDialogue: '“There’s no right answer — just your reality today.”',
    activityLevel1: "I'm just getting started (1-2 times)",
    activityLevel2: 'I exercise regularly (3-4 times)',
    activityLevel3: 'Running is part of my lifestyle (5-7 times)',
    howToDoit: 'How to do it',
    markComplete: 'Complete mission',
    close: 'Close',
    suggestedBy: 'Suggested by {petName}',
    myOwnGoals: 'My Own Goals',
    moodEnergetic: 'Energetic',
    moodCalm: 'Calm',
    moodTired: 'Tired',
    moodStressed: 'Stressed',
    energyLow: 'Low',
    energyHigh: 'High',
    chooseCompanion: 'Choose Companion',
    petGrowSub: 'They grow as you show up.',
    dog: 'Dog',
    cat: 'Cat',
    loseWeight: 'Lose weight',
    createRoutine: 'Create a routine',
    reduceStress: 'Reduce stress',
    becomeHealthier: 'Become healthier',
    mainGoalDialogue: '“This helps me focus our journey together.”',
    inviteShared: 'Invite shared!',
    howFeelingToday: 'How are you feeling today,',
    time10min: '10 minutes',
    time20min: '20 minutes',
    time30minplus: 'More than 30 min',
    timeDialogue: '“Even 10 minutes can make a difference!”',
    readyMission: "Ready for today's mission?",
    letsGo: "Let's go!",
    defaultPetSpeech: "Let's make it count!",
    forCompanion: 'For Your Companion',
    forReality: 'For Your Reality',
    premium: 'Premium',
    owned: 'Owned',
    redeemableReward: 'Redeemable reward',
    showedUpToday: 'You showed up today',
    tookCareOfYourself: 'You took care of yourself',
    petFeelsSupported: 'Your pet feels supported',
    sharePetWithLovedOnes: 'Share {petName} with your loved ones and grow together',
    tryPremium: 'Try HealthQuest Premium',
    premiumTrialSub: 'Experience the full journey with a 3-day free trial.',
    noAds: 'No ads forever',
    unlockRewards: 'Unlock real rewards & discounts',
    supportDev: 'Support HealthQuest development',
    tryForFree: 'Try for $0.00',
    maybeLater: 'Maybe later',
    stats: 'Stats',
    home: 'Home',
    shop: 'Shop',
    marketPlace: 'Marketplace',
    spendEffortOnJoy: 'Spend your effort on joy.',
    name: 'NAME',
    type: 'TYPE',
    breed: 'BREED',
    age: 'AGE',
    dayActive: '{X} Day active',
    daysActive: '{X} Days active',
    whatIsGoal: 'What is the goal?',
    goalPlaceholder: 'e.g. 5 min stretching...',
    category: 'Category',
    repeats: 'Repeats',
    chooseFromLibrary: 'Or choose from library',
    addMission: 'Add Mission',
    newMission: 'New Mission'
  },
  es: {
    start: 'Comenzar',
    continue: 'Continuar',
    startJourney: 'Empezar',
    nameYourPet: 'Nombra a tu mascota (opcional)',
    petNamingDialogue: '“Los nombres importan. Este es el comienzo de su viaje juntos.”',
    petGrow: 'Tu mascota crecerá contigo.',
    shareTitle: '¿Te gustaría cuidar de {petName} con alguien?',
    shareSub: 'Puedes invitar a alguien más tarde — el apoyo crece con el tiempo.',
    justMe: 'Solo yo',
    shareMyPet: 'Compartir mi mascota',
    copyLink: 'Copiar enlace',
    linkCopied: '¡Enlace copiado! 🔗',
    todayGoals: 'Metas de hoy',
    simulateNext: 'Simular siguiente día',
    petStatus: 'Estado de la mascota',
    dashboardWelcome: 'Me alegra que estés aquí. Vamos paso a paso hoy.',
    nextDayMessage: 'Cada día es una nueva oportunidad. Me alegra que estés aquí.',
    whatGender: 'Elige el género de tu mascota',
    petGenderDialogue: '“Tu mascota te refleja a ti, no a las etiquetas.”',
    male: 'Macho',
    female: 'Hembra',
    other: 'Otro',
    whatIsYourName: '¡Encantado de conocerte! ¿Cómo te llamas?',
    userNameDialogue: '“Usaré esto cuando hable contigo.”',
    userNamePlaceholder: 'Tu nombre...',
    customizationNote: 'Personalizaremos tu experiencia con esta información.',
    whatUserGender: '¿Cómo te identificas?',
    userMale: 'Masculino',
    userFemale: 'Femenino',
    userNonBinary: 'No binario',
    preferNotToAnswer: 'Prefiero no decir',
    intro1Title: 'Misiones IA',
    intro1Text: '“Crearé misiones diarias que se adapten a tu vida, energía y tiempo.”',
    intro2Title: 'Mejor Juntos',
    intro2Text: '“Puedes crecer solo, o compartir este viaje con alguien que te importe.”',
    intro3Title: 'Espacio Seguro',
    intro3Text: '“Faltar un día no dañará tu progreso. Siempre nos adaptamos.”',
    thinkingTitle: 'está pensando...',
    thinkingText: '“Creando tareas personalizadas basadas en tus gustos...”',
    userAgeTitle: '¿Cuál es tu rango de edad?',
    userAgeDialogue: '“Esto me ayuda a adaptar los desafíos de forma segura.”',
    userGenderTitle: 'Identidad de Género',
    userGenderDialogue: '“Solo si te sientes cómodo compartiendo.”',
    userAgeToday: '¿Cómo te sientes hoy,',
    userTimeToday: '¿Cuánto tiempo tienes hoy?',
    userEnergyToday: '¿Tu energía hoy?',
    thinkingText2: '“Creando tareas personalizadas basadas en tus gustos...”',
    userActivityTitle: '¿Con qué frecuencia sales a correr o caminar cada semana?',
    userActivityDialogue: '“No hay una respuesta correcta, solo tu realidad hoy.”',
    activityLevel1: 'Recién estoy comenzando (1-2 veces)',
    activityLevel2: 'Hago ejercicio regularmente (3-4 veces)',
    activityLevel3: 'Correr es parte de mi estilo de vida (5-7 veces)',
    howToDoit: 'Cómo hacerlo',
    markComplete: 'Completar misión',
    close: 'Cerrar',
    suggestedBy: 'Sugerido por {petName}',
    myOwnGoals: 'Mis metas propias',
    moodEnergetic: 'Enérgico',
    moodCalm: 'Tranquilo',
    moodTired: 'Cansado',
    moodStressed: 'Estresado',
    energyLow: 'Baja',
    energyHigh: 'Alta',
    chooseCompanion: 'Elige a tu compañero',
    petGrowSub: 'Crecen a medida que te presentas.',
    dog: 'Perro',
    cat: 'Gato',
    loseWeight: 'Perder peso',
    createRoutine: 'Crear una rutina',
    reduceStress: 'Reducir el estrés',
    becomeHealthier: 'Ser más saludable',
    mainGoalDialogue: '“Esto me ayuda a enfocar nuestro viaje juntos.”',
    inviteShared: '¡Invitación compartida!',
    howFeelingToday: '¿Cómo te sientes hoy,',
    time10min: '10 minutos',
    time20min: '20 minutos',
    time30minplus: 'Más de 30 min',
    timeDialogue: '“¡Incluso 10 minutos pueden marcar la diferencia!”',
    readyMission: "¿Listo para la misión de hoy?",
    letsGo: "¡Vamos!",
    defaultPetSpeech: "¡Hagamos que valga la pena!",
    forCompanion: 'Para Tu Mascota',
    forReality: 'Para Tu Realidad',
    premium: 'Premium',
    owned: 'Comprado',
    redeemableReward: 'Premio canjeable',
    showedUpToday: 'Viniste hoy',
    tookCareOfYourself: 'Te cuidaste',
    petFeelsSupported: 'Tu mascota se siente apoyada',
    sharePetWithLovedOnes: 'Comparte a {petName} con tus seres queridos y crezcan juntos',
    tryPremium: 'Prueba HealthQuest Premium',
    premiumTrialSub: 'Vive la experiencia completa con una prueba gratuita de 3 días.',
    noAds: 'Sin anuncios para siempre',
    unlockRewards: 'Desbloquea premios y descuentos reales',
    supportDev: 'Apoya el desarrollo de HealthQuest',
    tryForFree: 'Prueba por $0.00',
    maybeLater: 'Quizás más tarde',
    stats: 'Estadísticas',
    home: 'Inicio',
    shop: 'Tienda',
    marketPlace: 'Mercado',
    spendEffortOnJoy: 'Gasta tu esfuerzo en alegría.',
    name: 'NOMBRE',
    type: 'TIPO',
    breed: 'RAZA',
    age: 'EDAD',
    dayActive: '{X} Día activo',
    daysActive: '{X} Días activos',
    whatIsGoal: '¿Cuál es la meta?',
    goalPlaceholder: 'ej: 5 min estiramiento...',
    category: 'Categoría',
    repeats: 'Repite',
    chooseFromLibrary: 'O elige de la librería',
    addMission: 'Añadir Misión',
    newMission: 'Nueva Misión'
  }
};
